In [15]:
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv("./iris.csv")

In [17]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [18]:
enc = LabelEncoder()

In [19]:
enc.fit(df['Species'])

LabelEncoder()

In [20]:
df['Species'] = enc.transform(df['Species'])

In [21]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [35]:
columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'PetalWidthCm', 'Species']
label_column = 'Species'

In [30]:
dataset = tf.data.Dataset.from_tensor_slices(dict(df))

In [31]:
for row in dataset.take(3):
    print(row)

{'Id': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'SepalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=5.1>, 'SepalWidthCm': <tf.Tensor: shape=(), dtype=float64, numpy=3.5>, 'PetalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=1.4>, 'PetalWidthCm': <tf.Tensor: shape=(), dtype=float64, numpy=0.2>, 'Species': <tf.Tensor: shape=(), dtype=int32, numpy=0>}
{'Id': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'SepalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=4.9>, 'SepalWidthCm': <tf.Tensor: shape=(), dtype=float64, numpy=3.0>, 'PetalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=1.4>, 'PetalWidthCm': <tf.Tensor: shape=(), dtype=float64, numpy=0.2>, 'Species': <tf.Tensor: shape=(), dtype=int32, numpy=0>}
{'Id': <tf.Tensor: shape=(), dtype=int64, numpy=3>, 'SepalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=4.7>, 'SepalWidthCm': <tf.Tensor: shape=(), dtype=float64, numpy=3.2>, 'PetalLengthCm': <tf.Tensor: shape=(), dtype=float64, numpy=1.3>, 'PetalWidth

In [37]:
dataset = dataset.map(map_func=features_and_label)

In [38]:
dataset = dataset.shuffle(buffer_size=1000).repeat()

In [39]:
dataset

<RepeatDataset shapes: ({Id: (), SepalLengthCm: (), SepalWidthCm: (), PetalLengthCm: (), PetalWidthCm: ()}, ()), types: ({Id: tf.int64, SepalLengthCm: tf.float64, SepalWidthCm: tf.float64, PetalLengthCm: tf.float64, PetalWidthCm: tf.float64}, tf.int32)>