In [19]:
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder

In [35]:
df = pd.read_csv("./iris.csv")

In [36]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [37]:
enc = LabelEncoder()

In [38]:
enc.fit(df['Species'])

LabelEncoder()

In [39]:
df['Species'] = enc.transform(df['Species'])

In [40]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [48]:
columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'PetalWidthCm', 'Species']
label = 'Species'

In [42]:
df = df[columns]

In [43]:
df = tf.convert_to_tensor(df)

In [45]:
df[0]

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([5.1, 3.5, 1.4, 0.2, 0.2, 0. ])>

In [52]:
dataset = tf.data.Dataset.from_tensor_slices(df)

In [53]:
for row in dataset.take(3):
    print(row)

tf.Tensor([5.1 3.5 1.4 0.2 0.2 0. ], shape=(6,), dtype=float64)
tf.Tensor([4.9 3.  1.4 0.2 0.2 0. ], shape=(6,), dtype=float64)
tf.Tensor([4.7 3.2 1.3 0.2 0.2 0. ], shape=(6,), dtype=float64)


In [56]:
def features_and_label(row):
    label = row.pop(label)
    return row, label

In [ ]:
dataset = dataset.map(map_func=features_and_label)

In [50]:
dataset = dataset.shuffle(buffer_size=1000).repeat()